variables:
  - name: BuildParameters.RestoreBuildProjects
    value: '**/*.csproj'
  - name: BuildParameters.ArtifactName
    value: drop
trigger:
  branches:
    include:
      - refs/heads/master
name: $(date:yyyyMMdd)$(rev:.r)
resources:
  repositories:
    - repository: self
      type: git
      ref: refs/heads/master
jobs:
  - job: Job_1
    displayName: Agent job 1
    pool:
      vmImage: ubuntu-latest
    steps:
      - checkout: self
      - task: DotNetCoreCLI@2
        displayName: Restore
        inputs:
          command: restore
          projects: $(BuildParameters.RestoreBuildProjects)
      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          projects: $(BuildParameters.RestoreBuildProjects)
          arguments: --configuration $(BuildConfiguration)
      - task: DotNetCoreCLI@2
        displayName: Publish
        inputs:
          command: publish
          publishWebProjects: True
          projects: $(BuildParameters.RestoreBuildProjects)
          arguments: --configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory) /p:EnvironmentName=Production
          zipAfterPublish: True
      - task: PublishBuildArtifacts@1
        displayName: Publish Artifact
        condition: succeededOrFailed()
        inputs:
          PathtoPublish: $(build.artifactstagingdirectory)
          ArtifactName: $(BuildParameters.ArtifactName)
          TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'